services:
  - type: web
    name: chatterbox-yio
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_ORIGIN
        value: https://chatterbox-yio.onrender.com
